In [1]:
import pandas as pd
import sqlite3
import datetime
# Creamos la conexión con la base de datos
con = sqlite3.connect("seviBikes.db")
cur = con.cursor()

# Seleccionamos los datos
cur.execute("SELECT * From seviBikes")

# Lo almacenamos en una lista
data = cur.fetchall()
con.close()

In [83]:
# Creamos el dataframe
df = pd.DataFrame(data)
df=df.dropna()
df.head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65268 entries, 0 to 65519
Data columns (total 13 columns):
0     65268 non-null object
1     65268 non-null int64
2     65268 non-null int64
3     65268 non-null int64
4     65268 non-null int64
5     65268 non-null int64
6     65268 non-null object
7     65268 non-null float64
8     65268 non-null object
9     65268 non-null int64
10    65268 non-null float64
11    65268 non-null float64
12    65268 non-null object
dtypes: float64(3), int64(6), object(4)
memory usage: 7.0+ MB

In [84]:
# Renombramos las columnas
df.columns=["address","available_bike_stands","available_bikes","banking","bike_stands","bonus","contract_name",\
            "last_update","name","number","position_lat","position_lng","status"]
df.head(10)

,address,available_bike_stands,available_bikes,banking,bike_stands,bonus,contract_name,last_update,name,number,position_lat,position_lng,status
0,CALLE PARQUE DE DOÑANA - Aprox. Calle Corral d...,14,5,1,20,0,seville,1.581095e+12,194_CALLE PARQUE DE DOÑANA,194,37.418733,-5.973194,OPEN
1,AVENIDA REINA MERCEDES - Aprox. Facultad de In...,19,6,1,25,0,seville,1.581095e+12,126_AVENIDA REINA MERCEDES,126,37.358165,-5.986483,OPEN
2,PLAZA SAN AGUSTIN - Aprox. C/ Concepción,10,4,1,15,0,seville,1.581095e+12,073_PLAZA SAN AGUSTIN,73,37.389514,-5.984363,OPEN
3,CALLE ORFEBRE DOMINGUEZ VÁZQUEZ - Aprox. C/ Pi...,14,6,1,20,0,seville,1.581095e+12,186_CALLE ORFEBRE DOMINGUEZ VÁZQUEZ,186,37.408605,-5.973161,OPEN
4,PASEO CATALINA RIBERA - Aprox. C/ San Fernando,1,19,1,20,0,seville,1.581095e+12,100_PASEO CATALINA RIBERA,100,37.381516,-5.988999,OPEN
5,CALLE BETIS - Aprox. C/ Juan de Lugo,0,19,1,19,0,seville,1.581095e+12,096_CALLE BETIS,96,37.383541,-5.999911,OPEN
6,CALLE PAEZ DE RIVERA - Aprox. Paseo de la Palmera,15,5,1,20,0,seville,1.581095e+12,132_CALLE PAEZ DE RIVERA,132,37.363619,-5.984785,OPEN
7,Esquina Calle Pero Mingo,24,5,1,29,0,seville,1.581095e+12,256_MIGUEL MONTORO,256,37.386100,-5.910091,OPEN
8,CALLE LUIS MONTOTO - Aprox. C/ Maese Farfán,11,5,1,17,0,seville,1.581095e+12,082_CALLE LUIS MONTOTO,82,37.387098,-5.974843,OPEN
9,AVENIDA MUJER TRABAJADORA - Aprox. Avda Mirafl...,13,7,1,20,0,seville,1.581095e+12,202_AVENIDA MUJER TRABAJADORA,202,37.411467,-5.966763,OPEN

In [85]:
#Añadimos columna con la fecha ya convertida
df['datetime'] = pd.to_datetime(df["last_update"]/1000,unit='s')
df

,address,available_bike_stands,available_bikes,banking,bike_stands,bonus,contract_name,last_update,name,number,position_lat,position_lng,status,datetime
0,CALLE PARQUE DE DOÑANA - Aprox. Calle Corral d...,14,5,1,20,0,seville,1.581095e+12,194_CALLE PARQUE DE DOÑANA,194,37.418733,-5.973194,OPEN,2020-02-07 16:59:13
1,AVENIDA REINA MERCEDES - Aprox. Facultad de In...,19,6,1,25,0,seville,1.581095e+12,126_AVENIDA REINA MERCEDES,126,37.358165,-5.986483,OPEN,2020-02-07 17:00:49
2,PLAZA SAN AGUSTIN - Aprox. C/ Concepción,10,4,1,15,0,seville,1.581095e+12,073_PLAZA SAN AGUSTIN,73,37.389514,-5.984363,OPEN,2020-02-07 16:59:07
3,CALLE ORFEBRE DOMINGUEZ VÁZQUEZ - Aprox. C/ Pi...,14,6,1,20,0,seville,1.581095e+12,186_CALLE ORFEBRE DOMINGUEZ VÁZQUEZ,186,37.408605,-5.973161,OPEN,2020-02-07 17:03:50
4,PASEO CATALINA RIBERA - Aprox. C/ San Fernando,1,19,1,20,0,seville,1.581095e+12,100_PASEO CATALINA RIBERA,100,37.381516,-5.988999,OPEN,2020-02-07 17:06:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65515,CALLE ALHÓNDIGA - Aprox. Card. Cervantes,6,8,1,14,0,seville,1.581101e+12,065_CALLE ALHÓNDIGA,65,37.391299,-5.988140,OPEN,2020-02-07 18:44:21
65516,AVENIDA REINA MERCEDES - Aprox. C/ Profesor Ga...,10,10,1,20,0,seville,1.581101e+12,146_AVENIDA REINA MERCEDES,146,37.360101,-5.986313,OPEN,2020-02-07 18:46:28
65517,CALLE VIRGEN DE LUJÁN - Aprox. Glorieta las Ci...,5,12,1,17,0,seville,1.581101e+12,135_CALLE VIRGEN DE LUJÁN,135,37.374651,-5.993801,OPEN,2020-02-07 18:44:58
65518,CALLE ZORZAL - Aprox. Avenida de Andalucia,8,7,1,15,0,seville,1.581101e+12,215_CALLE ZORZAL,215,37.386641,-5.953981,OPEN,2020-02-07 18:42:57
65519,AVENIDA SOLEA - Aprox. C/ Media Granaína,11,7,1,18,0,seville,1.581101e+12,162_AVENIDA SOLEA,162,37.391540,-5.968466,OPEN,2020-02-07 18:46:40

In [87]:
day=[]
l= len(df)
for x in range(0,l-1):
    y = df["datetime"][x]
    print(y)
    print(y.strftime('%A'))
    day.append(y.strftime('%A'))
print(day)

2020-02-07 16:59:13
Friday
2020-02-07 17:00:49
Friday
2020-02-07 16:59:07
Friday
2020-02-07 17:03:50
Friday
2020-02-07 17:06:09
Friday
2020-02-07 16:59:34
Friday
2020-02-07 17:02:14
Friday
2020-02-07 17:01:58
Friday
2020-02-07 17:01:36
Friday
2020-02-07 16:59:22
Friday
2020-02-07 17:04:18
Friday
2020-02-07 17:08:35
Friday
2020-02-07 17:04:11
Friday
2020-02-07 17:02:05
Friday
2020-02-07 17:05:49
Friday
2020-02-07 17:05:51
Friday
2020-02-07 16:59:12
Friday
2020-02-07 17:08:48
Friday
2020-02-07 17:08:06
Friday
2020-02-07 17:02:21
Friday
2020-02-07 17:03:28
Friday
2020-02-07 17:07:55
Friday
2020-02-07 17:07:38
Friday
2020-02-07 17:00:30
Friday
2020-02-07 17:08:44
Friday
2020-02-07 17:01:25
Friday
2020-02-07 17:05:13
Friday
2020-02-07 17:05:34
Friday
2020-02-07 17:04:21
Friday
2020-02-07 17:05:06
Friday
2020-02-07 17:06:47
Friday
2020-02-07 17:01:33
Friday
2020-02-07 17:01:15
Friday
2020-02-07 13:38:40
Friday
2020-02-07 17:02:30
Friday
2020-02-07 17:06:57
Friday
2020-02-07 17:08:25
Friday
2020-02-07 16:59:22
Friday
2020-02-07 16:58:59
Friday
2020-02-07 17:02:18
Friday
2020-02-07 16:59:51
Friday
2020-02-07 17:08:52
Friday
2020-02-07 17:05:39
Friday
2020-02-07 17:06:13
Friday
2020-02-07 17:00:14
Friday
2020-02-07 17:07:50
Friday
2020-02-07 17:04:53
Friday
2020-02-07 17:06:27
Friday
2020-02-07 17:04:03
Friday
2020-02-07 17:06:39
Friday
2020-02-07 17:05:15
Friday
2020-02-07 17:04:28
Friday
2020-02-07 17:03:33
Friday
2020-02-07 17:01:33
Friday
2020-02-07 17:06:03
Friday
2020-02-07 17:06:33
Friday
2020-02-07 17:01:55
Friday
2020-02-07 17:06:15
Friday
2020-02-07 17:06:16
Friday
2020-02-07 17:05:49
Friday
2020-02-07 17:03:09
Friday
2020-02-07 17:02:42
Friday
2020-02-07 16:59:09
Friday
2020-02-07 17:08:46
Friday
2020-02-07 17:04:28
Friday
2020-02-07 17:06:10
Friday
2020-02-07 17:02:52
Friday
2020-02-07 17:08:45
Friday
2020-02-07 17:05:28
Friday
2020-02-07 16:58:50
Friday
2020-02-07 17:08:08
Friday
2020-02-07 17:08:57
Friday
2020-02-07 17:03:12
Friday
2020-02-07 17:00:40
Friday
2020-02-07 17:03:49
Friday
2020-02-07 17:08:04
Friday
2020-02-07 16:58:55
Friday
2020-02-07 17:03:37
Friday
2020-02-07 17:07:05
Friday
2020-02-07 17:03:09
Friday
2020-02-07 17:08:47
Friday
2020-02-07 17:02:42
Friday
2020-02-07 17:04:02
Friday
2020-02-07 17:08:30
Friday
2020-02-07 17:05:09
Friday
2020-02-07 17:03:19
Friday
2020-02-07 17:00:31
Friday
2020-02-07 17:02:42
Friday
2020-02-07 17:06:45
Friday
2020-02-07 17:07:11
Friday
2020-02-07 17:06:32
Friday
2020-02-07 17:07:37
Friday
2020-02-07 17:00:39
Friday
2020-02-07 17:00:52
Friday
2020-02-07 17:00:55
Friday
2020-02-07 17:08:47
Friday
2020-02-07 16:58:58
Friday
2020-02-07 17:07:33
Friday
2020-02-07 17:01:51
Friday
2020-02-07 17:02:57
Friday
2020-02-07 17:08:06
Friday

KeyError: 101

In [53]:
df_data= df["datetime"].astype(str).str.replace(" ", ":")
#Creamos las columnas de hora y fecha
df_temp = df_data.str.split(":", expand=True)
df["date"] = df_temp[0]
df["hour"]=df_temp[1]
df["time"]=df_temp[1]+":"+df_temp[2]+":"+df_temp[3]
df

,address,available_bike_stands,available_bikes,banking,bike_stands,bonus,contract_name,last_update,name,number,position_lat,position_lng,status,datetime,date,hour,time
0,CALLE PARQUE DE DOÑANA - Aprox. Calle Corral d...,14,5,1,20,0,seville,1.581095e+12,194_CALLE PARQUE DE DOÑANA,194,37.418733,-5.973194,OPEN,2020-02-07 16:59:13,2020-02-07,16,16:59:13
1,AVENIDA REINA MERCEDES - Aprox. Facultad de In...,19,6,1,25,0,seville,1.581095e+12,126_AVENIDA REINA MERCEDES,126,37.358165,-5.986483,OPEN,2020-02-07 17:00:49,2020-02-07,17,17:00:49
2,PLAZA SAN AGUSTIN - Aprox. C/ Concepción,10,4,1,15,0,seville,1.581095e+12,073_PLAZA SAN AGUSTIN,73,37.389514,-5.984363,OPEN,2020-02-07 16:59:07,2020-02-07,16,16:59:07
3,CALLE ORFEBRE DOMINGUEZ VÁZQUEZ - Aprox. C/ Pi...,14,6,1,20,0,seville,1.581095e+12,186_CALLE ORFEBRE DOMINGUEZ VÁZQUEZ,186,37.408605,-5.973161,OPEN,2020-02-07 17:03:50,2020-02-07,17,17:03:50
4,PASEO CATALINA RIBERA - Aprox. C/ San Fernando,1,19,1,20,0,seville,1.581095e+12,100_PASEO CATALINA RIBERA,100,37.381516,-5.988999,OPEN,2020-02-07 17:06:09,2020-02-07,17,17:06:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65515,CALLE ALHÓNDIGA - Aprox. Card. Cervantes,6,8,1,14,0,seville,1.581101e+12,065_CALLE ALHÓNDIGA,65,37.391299,-5.988140,OPEN,2020-02-07 18:44:21,2020-02-07,18,18:44:21
65516,AVENIDA REINA MERCEDES - Aprox. C/ Profesor Ga...,10,10,1,20,0,seville,1.581101e+12,146_AVENIDA REINA MERCEDES,146,37.360101,-5.986313,OPEN,2020-02-07 18:46:28,2020-02-07,18,18:46:28
65517,CALLE VIRGEN DE LUJÁN - Aprox. Glorieta las Ci...,5,12,1,17,0,seville,1.581101e+12,135_CALLE VIRGEN DE LUJÁN,135,37.374651,-5.993801,OPEN,2020-02-07 18:44:58,2020-02-07,18,18:44:58
65518,CALLE ZORZAL - Aprox. Avenida de Andalucia,8,7,1,15,0,seville,1.581101e+12,215_CALLE ZORZAL,215,37.386641,-5.953981,OPEN,2020-02-07 18:42:57,2020-02-07,18,18:42:57
65519,AVENIDA SOLEA - Aprox. C/ Media Granaína,11,7,1,18,0,seville,1.581101e+12,162_AVENIDA SOLEA,162,37.391540,-5.968466,OPEN,2020-02-07 18:46:40,2020-02-07,18,18:46:40

In [54]:
#Añadimos una nueva columna zona, esta indicará si la estación está en una zona universitaria o no.
#Zone tomará los siguientes valores:
#0: nada especial cercano
#1: hay cerca una facultad
#2: hay cerca un instituto
#3: hay cerca un estadio

zone=[]
for x in df["address"]:
    
    if (x.find("Facultad")!=-1 or x.find("Escuela")!=-1 ):
        zone.append(1)
    elif(x.find("Instituto")!=-1):
        zone.append(2)
    elif(x.find("Estadio")!=-1):
        zone.append(3)
    else:
        zone.append(0)
    
df["zone"]=zone
df

print(len(df[df["zone"]==0]))
print(len(df[df["zone"]==1]))
print(len(df[df["zone"]==2]))
print(len(df[df["zone"]==3]))

63504
1008
252
504

In [76]:
#Añadidmos una nueva columna "Holiday" en la que indicamos si el día es festivo o no. 
#Holiday: Boolean, 0 si no es festivo y 1 si lo es.
fiestas = ['2020-01-01','2020-01-06','2020-02-28','2020-04-09','2020-04-10','2020-04-29','2020-05-01','2020-06-11','2020-08-15','2020-10-15','2020-11-02','2020-12-07','2020-12-08']
df["holiday"]=[1 if x in fiestas else 0 for x in df["date"]]
df

,address,available_bike_stands,available_bikes,banking,bike_stands,bonus,contract_name,last_update,name,number,position_lat,position_lng,status,datetime,date,hour,time,zone,holiday
0,CALLE PARQUE DE DOÑANA - Aprox. Calle Corral d...,14,5,1,20,0,seville,1.581095e+12,194_CALLE PARQUE DE DOÑANA,194,37.418733,-5.973194,OPEN,2020-02-07 16:59:13,2020-02-07,16,16:59:13,0,0
1,AVENIDA REINA MERCEDES - Aprox. Facultad de In...,19,6,1,25,0,seville,1.581095e+12,126_AVENIDA REINA MERCEDES,126,37.358165,-5.986483,OPEN,2020-02-07 17:00:49,2020-02-07,17,17:00:49,1,0
2,PLAZA SAN AGUSTIN - Aprox. C/ Concepción,10,4,1,15,0,seville,1.581095e+12,073_PLAZA SAN AGUSTIN,73,37.389514,-5.984363,OPEN,2020-02-07 16:59:07,2020-02-07,16,16:59:07,0,0
3,CALLE ORFEBRE DOMINGUEZ VÁZQUEZ - Aprox. C/ Pi...,14,6,1,20,0,seville,1.581095e+12,186_CALLE ORFEBRE DOMINGUEZ VÁZQUEZ,186,37.408605,-5.973161,OPEN,2020-02-07 17:03:50,2020-02-07,17,17:03:50,0,0
4,PASEO CATALINA RIBERA - Aprox. C/ San Fernando,1,19,1,20,0,seville,1.581095e+12,100_PASEO CATALINA RIBERA,100,37.381516,-5.988999,OPEN,2020-02-07 17:06:09,2020-02-07,17,17:06:09,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65515,CALLE ALHÓNDIGA - Aprox. Card. Cervantes,6,8,1,14,0,seville,1.581101e+12,065_CALLE ALHÓNDIGA,65,37.391299,-5.988140,OPEN,2020-02-07 18:44:21,2020-02-07,18,18:44:21,0,0
65516,AVENIDA REINA MERCEDES - Aprox. C/ Profesor Ga...,10,10,1,20,0,seville,1.581101e+12,146_AVENIDA REINA MERCEDES,146,37.360101,-5.986313,OPEN,2020-02-07 18:46:28,2020-02-07,18,18:46:28,0,0
65517,CALLE VIRGEN DE LUJÁN - Aprox. Glorieta las Ci...,5,12,1,17,0,seville,1.581101e+12,135_CALLE VIRGEN DE LUJÁN,135,37.374651,-5.993801,OPEN,2020-02-07 18:44:58,2020-02-07,18,18:44:58,0,0
65518,CALLE ZORZAL - Aprox. Avenida de Andalucia,8,7,1,15,0,seville,1.581101e+12,215_CALLE ZORZAL,215,37.386641,-5.953981,OPEN,2020-02-07 18:42:57,2020-02-07,18,18:42:57,0,0
65519,AVENIDA SOLEA - Aprox. C/ Media Granaína,11,7,1,18,0,seville,1.581101e+12,162_AVENIDA SOLEA,162,37.391540,-5.968466,OPEN,2020-02-07 18:46:40,2020-02-07,18,18:46:40,0,0

In [73]:
#for x in [1,2,3]:
#    df.available_bikes[df['zone'] == x].plot(kind="kde")
    
#plt.legend({"Facultad", "Instituto", "Estadio"})
#plt.show()

In [16]:
#Una vez preprocesado los datos, lo guardamos en la base de datos con las nuevas columnas
#con = sqlite3.connect("seviBikes.db")
#cur= con.cursor()
#df.to_sql("seviBikes", con,if_exists = 'replace')